

document.write('<div class="VimgmainRight">')
document.write('<a href="//pal7.cubejoy.com/pal7sell/index.html" target="_blank" class="sellBuyBtn">')
document.write('<h6>预售购买</h6>')
document.write('<span>正式版预售开启</span>')
document.write('</a>')
document.write('<div class="VimgmainRbtn">')
document.write('<div>')
document.write('<a href="//store.cubejoy.com/html/en/store/goodsdetail/detail12622.html" target="_blank" class="btns demoFree">')
document.write('试玩版  免费领取')
document.write('</a>')
document.write('<a href="//app.cubejoy.com/download.html" target="_blank" class="btns cubedown">')
document.write('方块客户端下载')
document.write('</a>')
document.write('</div>')
document.write('<div class="VimgmainR-wei">')
document.write('<div class="Vimg-weixin">')
document.write('<img src="//pal7.cubejoy.com/images/weixinImg.png" alt="">')
document.write('<p>官方微信公众号</p>')
document.write('</div>')
document.write('<div class="Vimg-weibo">')
document.write('<img src="//pal7.cubejoy.com/images/weiboImg.png" alt="">')
document.write('<p>关注官方微博</p>')
document.write('</div>')
document.write('</div>')
document.write('</div>')
document.write('</div>')


